/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeploymentStatusHistory } from "./DeploymentStatusHistory";
import { DeploymentStatusHistoryCountArgs } from "./DeploymentStatusHistoryCountArgs";
import { DeploymentStatusHistoryFindManyArgs } from "./DeploymentStatusHistoryFindManyArgs";
import { DeploymentStatusHistoryFindUniqueArgs } from "./DeploymentStatusHistoryFindUniqueArgs";
import { CreateDeploymentStatusHistoryArgs } from "./CreateDeploymentStatusHistoryArgs";
import { UpdateDeploymentStatusHistoryArgs } from "./UpdateDeploymentStatusHistoryArgs";
import { DeleteDeploymentStatusHistoryArgs } from "./DeleteDeploymentStatusHistoryArgs";
import { DeploymentStatusHistoryService } from "../deploymentStatusHistory.service";
@graphql.Resolver(() => DeploymentStatusHistory)
export class DeploymentStatusHistoryResolverBase {
  constructor(protected readonly service: DeploymentStatusHistoryService) {}

  async _deploymentStatusHistoriesMeta(
    @graphql.Args() args: DeploymentStatusHistoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DeploymentStatusHistory])
  async deploymentStatusHistories(
    @graphql.Args() args: DeploymentStatusHistoryFindManyArgs
  ): Promise<DeploymentStatusHistory[]> {
    return this.service.deploymentStatusHistories(args);
  }

  @graphql.Query(() => DeploymentStatusHistory, { nullable: true })
  async deploymentStatusHistory(
    @graphql.Args() args: DeploymentStatusHistoryFindUniqueArgs
  ): Promise<DeploymentStatusHistory | null> {
    const result = await this.service.deploymentStatusHistory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DeploymentStatusHistory)
  async createDeploymentStatusHistory(
    @graphql.Args() args: CreateDeploymentStatusHistoryArgs
  ): Promise<DeploymentStatusHistory> {
    return await this.service.createDeploymentStatusHistory({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => DeploymentStatusHistory)
  async updateDeploymentStatusHistory(
    @graphql.Args() args: UpdateDeploymentStatusHistoryArgs
  ): Promise<DeploymentStatusHistory | null> {
    try {
      return await this.service.updateDeploymentStatusHistory({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DeploymentStatusHistory)
  async deleteDeploymentStatusHistory(
    @graphql.Args() args: DeleteDeploymentStatusHistoryArgs
  ): Promise<DeploymentStatusHistory | null> {
    try {
      return await this.service.deleteDeploymentStatusHistory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
