/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  DeploymentStatusHistory as PrismaDeploymentStatusHistory,
} from "@prisma/client";

export class DeploymentStatusHistoryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DeploymentStatusHistoryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.deploymentStatusHistory.count(args);
  }

  async deploymentStatusHistories(
    args: Prisma.DeploymentStatusHistoryFindManyArgs
  ): Promise<PrismaDeploymentStatusHistory[]> {
    return this.prisma.deploymentStatusHistory.findMany(args);
  }
  async deploymentStatusHistory(
    args: Prisma.DeploymentStatusHistoryFindUniqueArgs
  ): Promise<PrismaDeploymentStatusHistory | null> {
    return this.prisma.deploymentStatusHistory.findUnique(args);
  }
  async createDeploymentStatusHistory(
    args: Prisma.DeploymentStatusHistoryCreateArgs
  ): Promise<PrismaDeploymentStatusHistory> {
    return this.prisma.deploymentStatusHistory.create(args);
  }
  async updateDeploymentStatusHistory(
    args: Prisma.DeploymentStatusHistoryUpdateArgs
  ): Promise<PrismaDeploymentStatusHistory> {
    return this.prisma.deploymentStatusHistory.update(args);
  }
  async deleteDeploymentStatusHistory(
    args: Prisma.DeploymentStatusHistoryDeleteArgs
  ): Promise<PrismaDeploymentStatusHistory> {
    return this.prisma.deploymentStatusHistory.delete(args);
  }
}
