/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DeploymentStatusHistoryService } from "../deploymentStatusHistory.service";
import { DeploymentStatusHistoryCreateInput } from "./DeploymentStatusHistoryCreateInput";
import { DeploymentStatusHistory } from "./DeploymentStatusHistory";
import { DeploymentStatusHistoryFindManyArgs } from "./DeploymentStatusHistoryFindManyArgs";
import { DeploymentStatusHistoryWhereUniqueInput } from "./DeploymentStatusHistoryWhereUniqueInput";
import { DeploymentStatusHistoryUpdateInput } from "./DeploymentStatusHistoryUpdateInput";

export class DeploymentStatusHistoryControllerBase {
  constructor(protected readonly service: DeploymentStatusHistoryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DeploymentStatusHistory })
  async createDeploymentStatusHistory(
    @common.Body() data: DeploymentStatusHistoryCreateInput
  ): Promise<DeploymentStatusHistory> {
    return await this.service.createDeploymentStatusHistory({
      data: data,
      select: {
        createdAt: true,
        deployment: true,
        details: true,
        id: true,
        status: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [DeploymentStatusHistory] })
  @ApiNestedQuery(DeploymentStatusHistoryFindManyArgs)
  async deploymentStatusHistories(
    @common.Req() request: Request
  ): Promise<DeploymentStatusHistory[]> {
    const args = plainToClass(
      DeploymentStatusHistoryFindManyArgs,
      request.query
    );
    return this.service.deploymentStatusHistories({
      ...args,
      select: {
        createdAt: true,
        deployment: true,
        details: true,
        id: true,
        status: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DeploymentStatusHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deploymentStatusHistory(
    @common.Param() params: DeploymentStatusHistoryWhereUniqueInput
  ): Promise<DeploymentStatusHistory | null> {
    const result = await this.service.deploymentStatusHistory({
      where: params,
      select: {
        createdAt: true,
        deployment: true,
        details: true,
        id: true,
        status: true,
        timestamp: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DeploymentStatusHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDeploymentStatusHistory(
    @common.Param() params: DeploymentStatusHistoryWhereUniqueInput,
    @common.Body() data: DeploymentStatusHistoryUpdateInput
  ): Promise<DeploymentStatusHistory | null> {
    try {
      return await this.service.updateDeploymentStatusHistory({
        where: params,
        data: data,
        select: {
          createdAt: true,
          deployment: true,
          details: true,
          id: true,
          status: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DeploymentStatusHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDeploymentStatusHistory(
    @common.Param() params: DeploymentStatusHistoryWhereUniqueInput
  ): Promise<DeploymentStatusHistory | null> {
    try {
      return await this.service.deleteDeploymentStatusHistory({
        where: params,
        select: {
          createdAt: true,
          deployment: true,
          details: true,
          id: true,
          status: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
