/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Deployment as PrismaDeployment,
  PromptHandler as PrismaPromptHandler,
  UserProfile as PrismaUserProfile,
} from "@prisma/client";

import { StartDeploymentInput } from "../StartDeploymentInput";
import { StartDeploymentResult } from "../StartDeploymentResult";
import { SyncStatusInput } from "../SyncStatusInput";
import { SyncStatusResult } from "../SyncStatusResult";

export class DeploymentServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DeploymentCountArgs, "select">
  ): Promise<number> {
    return this.prisma.deployment.count(args);
  }

  async deployments(
    args: Prisma.DeploymentFindManyArgs
  ): Promise<PrismaDeployment[]> {
    return this.prisma.deployment.findMany(args);
  }
  async deployment(
    args: Prisma.DeploymentFindUniqueArgs
  ): Promise<PrismaDeployment | null> {
    return this.prisma.deployment.findUnique(args);
  }
  async createDeployment(
    args: Prisma.DeploymentCreateArgs
  ): Promise<PrismaDeployment> {
    return this.prisma.deployment.create(args);
  }
  async updateDeployment(
    args: Prisma.DeploymentUpdateArgs
  ): Promise<PrismaDeployment> {
    return this.prisma.deployment.update(args);
  }
  async deleteDeployment(
    args: Prisma.DeploymentDeleteArgs
  ): Promise<PrismaDeployment> {
    return this.prisma.deployment.delete(args);
  }

  async findPromptHandlers(
    parentId: string,
    args: Prisma.PromptHandlerFindManyArgs
  ): Promise<PrismaPromptHandler[]> {
    return this.prisma.deployment
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .promptHandlers(args);
  }

  async getUserProfile(parentId: string): Promise<PrismaUserProfile | null> {
    return this.prisma.deployment
      .findUnique({
        where: { id: parentId },
      })
      .userProfile();
  }
  async StartDeployment(
    args: StartDeploymentInput
  ): Promise<StartDeploymentResult> {
    throw new Error("Not implemented");
  }
  async SyncDeploymentStatus(args: SyncStatusInput): Promise<SyncStatusResult> {
    throw new Error("Not implemented");
  }
}
