/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { PromptHandlerCreateNestedManyWithoutDeploymentsInput } from "./PromptHandlerCreateNestedManyWithoutDeploymentsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumDeploymentStatus } from "./EnumDeploymentStatus";
import { UserProfileWhereUniqueInput } from "../../userProfile/base/UserProfileWhereUniqueInput";

@InputType()
class DeploymentCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  autoTerminateAt?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  environment?: string | null;

  @ApiProperty({
    required: false,
    type: () => PromptHandlerCreateNestedManyWithoutDeploymentsInput,
  })
  @ValidateNested()
  @Type(() => PromptHandlerCreateNestedManyWithoutDeploymentsInput)
  @IsOptional()
  @Field(() => PromptHandlerCreateNestedManyWithoutDeploymentsInput, {
    nullable: true,
  })
  promptHandlers?: PromptHandlerCreateNestedManyWithoutDeploymentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  region?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  requestPrompt?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  resolvedConfig?: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumDeploymentStatus,
  })
  @IsEnum(EnumDeploymentStatus)
  @IsOptional()
  @Field(() => EnumDeploymentStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => UserProfileWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserProfileWhereUniqueInput)
  @IsOptional()
  @Field(() => UserProfileWhereUniqueInput, {
    nullable: true,
  })
  userProfile?: UserProfileWhereUniqueInput | null;
}

export { DeploymentCreateInput as DeploymentCreateInput };
