/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DeploymentService } from "../deployment.service";
import { DeploymentCreateInput } from "./DeploymentCreateInput";
import { Deployment } from "./Deployment";
import { DeploymentFindManyArgs } from "./DeploymentFindManyArgs";
import { DeploymentWhereUniqueInput } from "./DeploymentWhereUniqueInput";
import { DeploymentUpdateInput } from "./DeploymentUpdateInput";
import { PromptHandlerFindManyArgs } from "../../promptHandler/base/PromptHandlerFindManyArgs";
import { PromptHandler } from "../../promptHandler/base/PromptHandler";
import { PromptHandlerWhereUniqueInput } from "../../promptHandler/base/PromptHandlerWhereUniqueInput";
import { StartDeploymentInput } from "../StartDeploymentInput";
import { StartDeploymentResult } from "../StartDeploymentResult";
import { SyncStatusInput } from "../SyncStatusInput";
import { SyncStatusResult } from "../SyncStatusResult";

export class DeploymentControllerBase {
  constructor(protected readonly service: DeploymentService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Deployment })
  async createDeployment(
    @common.Body() data: DeploymentCreateInput
  ): Promise<Deployment> {
    return await this.service.createDeployment({
      data: {
        ...data,

        userProfile: data.userProfile
          ? {
              connect: data.userProfile,
            }
          : undefined,
      },
      select: {
        autoTerminateAt: true,
        createdAt: true,
        environment: true,
        id: true,
        region: true,
        requestPrompt: true,
        resolvedConfig: true,
        status: true,
        updatedAt: true,

        userProfile: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Deployment] })
  @ApiNestedQuery(DeploymentFindManyArgs)
  async deployments(@common.Req() request: Request): Promise<Deployment[]> {
    const args = plainToClass(DeploymentFindManyArgs, request.query);
    return this.service.deployments({
      ...args,
      select: {
        autoTerminateAt: true,
        createdAt: true,
        environment: true,
        id: true,
        region: true,
        requestPrompt: true,
        resolvedConfig: true,
        status: true,
        updatedAt: true,

        userProfile: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Deployment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deployment(
    @common.Param() params: DeploymentWhereUniqueInput
  ): Promise<Deployment | null> {
    const result = await this.service.deployment({
      where: params,
      select: {
        autoTerminateAt: true,
        createdAt: true,
        environment: true,
        id: true,
        region: true,
        requestPrompt: true,
        resolvedConfig: true,
        status: true,
        updatedAt: true,

        userProfile: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Deployment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDeployment(
    @common.Param() params: DeploymentWhereUniqueInput,
    @common.Body() data: DeploymentUpdateInput
  ): Promise<Deployment | null> {
    try {
      return await this.service.updateDeployment({
        where: params,
        data: {
          ...data,

          userProfile: data.userProfile
            ? {
                connect: data.userProfile,
              }
            : undefined,
        },
        select: {
          autoTerminateAt: true,
          createdAt: true,
          environment: true,
          id: true,
          region: true,
          requestPrompt: true,
          resolvedConfig: true,
          status: true,
          updatedAt: true,

          userProfile: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Deployment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDeployment(
    @common.Param() params: DeploymentWhereUniqueInput
  ): Promise<Deployment | null> {
    try {
      return await this.service.deleteDeployment({
        where: params,
        select: {
          autoTerminateAt: true,
          createdAt: true,
          environment: true,
          id: true,
          region: true,
          requestPrompt: true,
          resolvedConfig: true,
          status: true,
          updatedAt: true,

          userProfile: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/promptHandlers")
  @ApiNestedQuery(PromptHandlerFindManyArgs)
  async findPromptHandlers(
    @common.Req() request: Request,
    @common.Param() params: DeploymentWhereUniqueInput
  ): Promise<PromptHandler[]> {
    const query = plainToClass(PromptHandlerFindManyArgs, request.query);
    const results = await this.service.findPromptHandlers(params.id, {
      ...query,
      select: {
        createdAt: true,

        deployment: {
          select: {
            id: true,
          },
        },

        detectedOs: true,
        id: true,
        inputPrompt: true,
        parsedInstructions: true,
        resourcesRequested: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/promptHandlers")
  async connectPromptHandlers(
    @common.Param() params: DeploymentWhereUniqueInput,
    @common.Body() body: PromptHandlerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      promptHandlers: {
        connect: body,
      },
    };
    await this.service.updateDeployment({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/promptHandlers")
  async updatePromptHandlers(
    @common.Param() params: DeploymentWhereUniqueInput,
    @common.Body() body: PromptHandlerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      promptHandlers: {
        set: body,
      },
    };
    await this.service.updateDeployment({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/promptHandlers")
  async disconnectPromptHandlers(
    @common.Param() params: DeploymentWhereUniqueInput,
    @common.Body() body: PromptHandlerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      promptHandlers: {
        disconnect: body,
      },
    };
    await this.service.updateDeployment({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Post("/start")
  @swagger.ApiOkResponse({
    type: StartDeploymentResult,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async StartDeployment(
    @common.Body()
    body: StartDeploymentInput
  ): Promise<StartDeploymentResult> {
    return this.service.StartDeployment(body);
  }

  @common.Post("/sync-status")
  @swagger.ApiOkResponse({
    type: SyncStatusResult,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async SyncDeploymentStatus(
    @common.Body()
    body: SyncStatusInput
  ): Promise<SyncStatusResult> {
    return this.service.SyncDeploymentStatus(body);
  }
}
