/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { GcpConnection } from "./GcpConnection";
import { GcpConnectionCountArgs } from "./GcpConnectionCountArgs";
import { GcpConnectionFindManyArgs } from "./GcpConnectionFindManyArgs";
import { GcpConnectionFindUniqueArgs } from "./GcpConnectionFindUniqueArgs";
import { CreateGcpConnectionArgs } from "./CreateGcpConnectionArgs";
import { UpdateGcpConnectionArgs } from "./UpdateGcpConnectionArgs";
import { DeleteGcpConnectionArgs } from "./DeleteGcpConnectionArgs";
import { GcpConnectionService } from "../gcpConnection.service";
@graphql.Resolver(() => GcpConnection)
export class GcpConnectionResolverBase {
  constructor(protected readonly service: GcpConnectionService) {}

  async _gcpConnectionsMeta(
    @graphql.Args() args: GcpConnectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [GcpConnection])
  async gcpConnections(
    @graphql.Args() args: GcpConnectionFindManyArgs
  ): Promise<GcpConnection[]> {
    return this.service.gcpConnections(args);
  }

  @graphql.Query(() => GcpConnection, { nullable: true })
  async gcpConnection(
    @graphql.Args() args: GcpConnectionFindUniqueArgs
  ): Promise<GcpConnection | null> {
    const result = await this.service.gcpConnection(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => GcpConnection)
  async createGcpConnection(
    @graphql.Args() args: CreateGcpConnectionArgs
  ): Promise<GcpConnection> {
    return await this.service.createGcpConnection({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => GcpConnection)
  async updateGcpConnection(
    @graphql.Args() args: UpdateGcpConnectionArgs
  ): Promise<GcpConnection | null> {
    try {
      return await this.service.updateGcpConnection({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => GcpConnection)
  async deleteGcpConnection(
    @graphql.Args() args: DeleteGcpConnectionArgs
  ): Promise<GcpConnection | null> {
    try {
      return await this.service.deleteGcpConnection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
