/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, GcpConnection as PrismaGcpConnection } from "@prisma/client";

export class GcpConnectionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.GcpConnectionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.gcpConnection.count(args);
  }

  async gcpConnections(
    args: Prisma.GcpConnectionFindManyArgs
  ): Promise<PrismaGcpConnection[]> {
    return this.prisma.gcpConnection.findMany(args);
  }
  async gcpConnection(
    args: Prisma.GcpConnectionFindUniqueArgs
  ): Promise<PrismaGcpConnection | null> {
    return this.prisma.gcpConnection.findUnique(args);
  }
  async createGcpConnection(
    args: Prisma.GcpConnectionCreateArgs
  ): Promise<PrismaGcpConnection> {
    return this.prisma.gcpConnection.create(args);
  }
  async updateGcpConnection(
    args: Prisma.GcpConnectionUpdateArgs
  ): Promise<PrismaGcpConnection> {
    return this.prisma.gcpConnection.update(args);
  }
  async deleteGcpConnection(
    args: Prisma.GcpConnectionDeleteArgs
  ): Promise<PrismaGcpConnection> {
    return this.prisma.gcpConnection.delete(args);
  }
}
