/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GcpConnectionService } from "../gcpConnection.service";
import { GcpConnectionCreateInput } from "./GcpConnectionCreateInput";
import { GcpConnection } from "./GcpConnection";
import { GcpConnectionFindManyArgs } from "./GcpConnectionFindManyArgs";
import { GcpConnectionWhereUniqueInput } from "./GcpConnectionWhereUniqueInput";
import { GcpConnectionUpdateInput } from "./GcpConnectionUpdateInput";

export class GcpConnectionControllerBase {
  constructor(protected readonly service: GcpConnectionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GcpConnection })
  async createGcpConnection(
    @common.Body() data: GcpConnectionCreateInput
  ): Promise<GcpConnection> {
    return await this.service.createGcpConnection({
      data: data,
      select: {
        createdAt: true,
        id: true,
        projectId: true,
        region: true,
        serviceAccountJson: true,
        updatedAt: true,
        userProfile: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [GcpConnection] })
  @ApiNestedQuery(GcpConnectionFindManyArgs)
  async gcpConnections(
    @common.Req() request: Request
  ): Promise<GcpConnection[]> {
    const args = plainToClass(GcpConnectionFindManyArgs, request.query);
    return this.service.gcpConnections({
      ...args,
      select: {
        createdAt: true,
        id: true,
        projectId: true,
        region: true,
        serviceAccountJson: true,
        updatedAt: true,
        userProfile: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GcpConnection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async gcpConnection(
    @common.Param() params: GcpConnectionWhereUniqueInput
  ): Promise<GcpConnection | null> {
    const result = await this.service.gcpConnection({
      where: params,
      select: {
        createdAt: true,
        id: true,
        projectId: true,
        region: true,
        serviceAccountJson: true,
        updatedAt: true,
        userProfile: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GcpConnection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateGcpConnection(
    @common.Param() params: GcpConnectionWhereUniqueInput,
    @common.Body() data: GcpConnectionUpdateInput
  ): Promise<GcpConnection | null> {
    try {
      return await this.service.updateGcpConnection({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          projectId: true,
          region: true,
          serviceAccountJson: true,
          updatedAt: true,
          userProfile: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GcpConnection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteGcpConnection(
    @common.Param() params: GcpConnectionWhereUniqueInput
  ): Promise<GcpConnection | null> {
    try {
      return await this.service.deleteGcpConnection({
        where: params,
        select: {
          createdAt: true,
          id: true,
          projectId: true,
          region: true,
          serviceAccountJson: true,
          updatedAt: true,
          userProfile: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
