/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { InstanceTemplate } from "./InstanceTemplate";
import { InstanceTemplateCountArgs } from "./InstanceTemplateCountArgs";
import { InstanceTemplateFindManyArgs } from "./InstanceTemplateFindManyArgs";
import { InstanceTemplateFindUniqueArgs } from "./InstanceTemplateFindUniqueArgs";
import { CreateInstanceTemplateArgs } from "./CreateInstanceTemplateArgs";
import { UpdateInstanceTemplateArgs } from "./UpdateInstanceTemplateArgs";
import { DeleteInstanceTemplateArgs } from "./DeleteInstanceTemplateArgs";
import { Region } from "../../region/base/Region";
import { InstanceTemplateService } from "../instanceTemplate.service";
@graphql.Resolver(() => InstanceTemplate)
export class InstanceTemplateResolverBase {
  constructor(protected readonly service: InstanceTemplateService) {}

  async _instanceTemplatesMeta(
    @graphql.Args() args: InstanceTemplateCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [InstanceTemplate])
  async instanceTemplates(
    @graphql.Args() args: InstanceTemplateFindManyArgs
  ): Promise<InstanceTemplate[]> {
    return this.service.instanceTemplates(args);
  }

  @graphql.Query(() => InstanceTemplate, { nullable: true })
  async instanceTemplate(
    @graphql.Args() args: InstanceTemplateFindUniqueArgs
  ): Promise<InstanceTemplate | null> {
    const result = await this.service.instanceTemplate(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => InstanceTemplate)
  async createInstanceTemplate(
    @graphql.Args() args: CreateInstanceTemplateArgs
  ): Promise<InstanceTemplate> {
    return await this.service.createInstanceTemplate({
      ...args,
      data: {
        ...args.data,

        region: args.data.region
          ? {
              connect: args.data.region,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => InstanceTemplate)
  async updateInstanceTemplate(
    @graphql.Args() args: UpdateInstanceTemplateArgs
  ): Promise<InstanceTemplate | null> {
    try {
      return await this.service.updateInstanceTemplate({
        ...args,
        data: {
          ...args.data,

          region: args.data.region
            ? {
                connect: args.data.region,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => InstanceTemplate)
  async deleteInstanceTemplate(
    @graphql.Args() args: DeleteInstanceTemplateArgs
  ): Promise<InstanceTemplate | null> {
    try {
      return await this.service.deleteInstanceTemplate(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Region, {
    nullable: true,
    name: "region",
  })
  async getRegion(
    @graphql.Parent() parent: InstanceTemplate
  ): Promise<Region | null> {
    const result = await this.service.getRegion(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
