/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ResourceTagService } from "../resourceTag.service";
import { ResourceTagCreateInput } from "./ResourceTagCreateInput";
import { ResourceTag } from "./ResourceTag";
import { ResourceTagFindManyArgs } from "./ResourceTagFindManyArgs";
import { ResourceTagWhereUniqueInput } from "./ResourceTagWhereUniqueInput";
import { ResourceTagUpdateInput } from "./ResourceTagUpdateInput";

export class ResourceTagControllerBase {
  constructor(protected readonly service: ResourceTagService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ResourceTag })
  async createResourceTag(
    @common.Body() data: ResourceTagCreateInput
  ): Promise<ResourceTag> {
    return await this.service.createResourceTag({
      data: data,
      select: {
        createdAt: true,
        id: true,
        key: true,
        resourceId: true,
        resourceType: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ResourceTag] })
  @ApiNestedQuery(ResourceTagFindManyArgs)
  async resourceTags(@common.Req() request: Request): Promise<ResourceTag[]> {
    const args = plainToClass(ResourceTagFindManyArgs, request.query);
    return this.service.resourceTags({
      ...args,
      select: {
        createdAt: true,
        id: true,
        key: true,
        resourceId: true,
        resourceType: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ResourceTag })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async resourceTag(
    @common.Param() params: ResourceTagWhereUniqueInput
  ): Promise<ResourceTag | null> {
    const result = await this.service.resourceTag({
      where: params,
      select: {
        createdAt: true,
        id: true,
        key: true,
        resourceId: true,
        resourceType: true,
        updatedAt: true,
        value: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ResourceTag })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateResourceTag(
    @common.Param() params: ResourceTagWhereUniqueInput,
    @common.Body() data: ResourceTagUpdateInput
  ): Promise<ResourceTag | null> {
    try {
      return await this.service.updateResourceTag({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          key: true,
          resourceId: true,
          resourceType: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ResourceTag })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteResourceTag(
    @common.Param() params: ResourceTagWhereUniqueInput
  ): Promise<ResourceTag | null> {
    try {
      return await this.service.deleteResourceTag({
        where: params,
        select: {
          createdAt: true,
          id: true,
          key: true,
          resourceId: true,
          resourceType: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
