/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, ResourceTag as PrismaResourceTag } from "@prisma/client";

export class ResourceTagServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ResourceTagCountArgs, "select">
  ): Promise<number> {
    return this.prisma.resourceTag.count(args);
  }

  async resourceTags(
    args: Prisma.ResourceTagFindManyArgs
  ): Promise<PrismaResourceTag[]> {
    return this.prisma.resourceTag.findMany(args);
  }
  async resourceTag(
    args: Prisma.ResourceTagFindUniqueArgs
  ): Promise<PrismaResourceTag | null> {
    return this.prisma.resourceTag.findUnique(args);
  }
  async createResourceTag(
    args: Prisma.ResourceTagCreateArgs
  ): Promise<PrismaResourceTag> {
    return this.prisma.resourceTag.create(args);
  }
  async updateResourceTag(
    args: Prisma.ResourceTagUpdateArgs
  ): Promise<PrismaResourceTag> {
    return this.prisma.resourceTag.update(args);
  }
  async deleteResourceTag(
    args: Prisma.ResourceTagDeleteArgs
  ): Promise<PrismaResourceTag> {
    return this.prisma.resourceTag.delete(args);
  }
}
