/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ResourceTag } from "./ResourceTag";
import { ResourceTagCountArgs } from "./ResourceTagCountArgs";
import { ResourceTagFindManyArgs } from "./ResourceTagFindManyArgs";
import { ResourceTagFindUniqueArgs } from "./ResourceTagFindUniqueArgs";
import { CreateResourceTagArgs } from "./CreateResourceTagArgs";
import { UpdateResourceTagArgs } from "./UpdateResourceTagArgs";
import { DeleteResourceTagArgs } from "./DeleteResourceTagArgs";
import { ResourceTagService } from "../resourceTag.service";
@graphql.Resolver(() => ResourceTag)
export class ResourceTagResolverBase {
  constructor(protected readonly service: ResourceTagService) {}

  async _resourceTagsMeta(
    @graphql.Args() args: ResourceTagCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ResourceTag])
  async resourceTags(
    @graphql.Args() args: ResourceTagFindManyArgs
  ): Promise<ResourceTag[]> {
    return this.service.resourceTags(args);
  }

  @graphql.Query(() => ResourceTag, { nullable: true })
  async resourceTag(
    @graphql.Args() args: ResourceTagFindUniqueArgs
  ): Promise<ResourceTag | null> {
    const result = await this.service.resourceTag(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ResourceTag)
  async createResourceTag(
    @graphql.Args() args: CreateResourceTagArgs
  ): Promise<ResourceTag> {
    return await this.service.createResourceTag({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => ResourceTag)
  async updateResourceTag(
    @graphql.Args() args: UpdateResourceTagArgs
  ): Promise<ResourceTag | null> {
    try {
      return await this.service.updateResourceTag({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ResourceTag)
  async deleteResourceTag(
    @graphql.Args() args: DeleteResourceTagArgs
  ): Promise<ResourceTag | null> {
    try {
      return await this.service.deleteResourceTag(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
