/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AzureConnectionService } from "../azureConnection.service";
import { AzureConnectionCreateInput } from "./AzureConnectionCreateInput";
import { AzureConnection } from "./AzureConnection";
import { AzureConnectionFindManyArgs } from "./AzureConnectionFindManyArgs";
import { AzureConnectionWhereUniqueInput } from "./AzureConnectionWhereUniqueInput";
import { AzureConnectionUpdateInput } from "./AzureConnectionUpdateInput";

export class AzureConnectionControllerBase {
  constructor(protected readonly service: AzureConnectionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AzureConnection })
  async createAzureConnection(
    @common.Body() data: AzureConnectionCreateInput
  ): Promise<AzureConnection> {
    return await this.service.createAzureConnection({
      data: data,
      select: {
        clientId: true,
        clientSecret: true,
        createdAt: true,
        id: true,
        region: true,
        subscriptionId: true,
        tenantId: true,
        updatedAt: true,
        userProfile: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AzureConnection] })
  @ApiNestedQuery(AzureConnectionFindManyArgs)
  async azureConnections(
    @common.Req() request: Request
  ): Promise<AzureConnection[]> {
    const args = plainToClass(AzureConnectionFindManyArgs, request.query);
    return this.service.azureConnections({
      ...args,
      select: {
        clientId: true,
        clientSecret: true,
        createdAt: true,
        id: true,
        region: true,
        subscriptionId: true,
        tenantId: true,
        updatedAt: true,
        userProfile: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AzureConnection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async azureConnection(
    @common.Param() params: AzureConnectionWhereUniqueInput
  ): Promise<AzureConnection | null> {
    const result = await this.service.azureConnection({
      where: params,
      select: {
        clientId: true,
        clientSecret: true,
        createdAt: true,
        id: true,
        region: true,
        subscriptionId: true,
        tenantId: true,
        updatedAt: true,
        userProfile: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AzureConnection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAzureConnection(
    @common.Param() params: AzureConnectionWhereUniqueInput,
    @common.Body() data: AzureConnectionUpdateInput
  ): Promise<AzureConnection | null> {
    try {
      return await this.service.updateAzureConnection({
        where: params,
        data: data,
        select: {
          clientId: true,
          clientSecret: true,
          createdAt: true,
          id: true,
          region: true,
          subscriptionId: true,
          tenantId: true,
          updatedAt: true,
          userProfile: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AzureConnection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAzureConnection(
    @common.Param() params: AzureConnectionWhereUniqueInput
  ): Promise<AzureConnection | null> {
    try {
      return await this.service.deleteAzureConnection({
        where: params,
        select: {
          clientId: true,
          clientSecret: true,
          createdAt: true,
          id: true,
          region: true,
          subscriptionId: true,
          tenantId: true,
          updatedAt: true,
          userProfile: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
