/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  AzureConnection as PrismaAzureConnection,
} from "@prisma/client";

export class AzureConnectionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AzureConnectionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.azureConnection.count(args);
  }

  async azureConnections(
    args: Prisma.AzureConnectionFindManyArgs
  ): Promise<PrismaAzureConnection[]> {
    return this.prisma.azureConnection.findMany(args);
  }
  async azureConnection(
    args: Prisma.AzureConnectionFindUniqueArgs
  ): Promise<PrismaAzureConnection | null> {
    return this.prisma.azureConnection.findUnique(args);
  }
  async createAzureConnection(
    args: Prisma.AzureConnectionCreateArgs
  ): Promise<PrismaAzureConnection> {
    return this.prisma.azureConnection.create(args);
  }
  async updateAzureConnection(
    args: Prisma.AzureConnectionUpdateArgs
  ): Promise<PrismaAzureConnection> {
    return this.prisma.azureConnection.update(args);
  }
  async deleteAzureConnection(
    args: Prisma.AzureConnectionDeleteArgs
  ): Promise<PrismaAzureConnection> {
    return this.prisma.azureConnection.delete(args);
  }
}
