/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AzureConnection } from "./AzureConnection";
import { AzureConnectionCountArgs } from "./AzureConnectionCountArgs";
import { AzureConnectionFindManyArgs } from "./AzureConnectionFindManyArgs";
import { AzureConnectionFindUniqueArgs } from "./AzureConnectionFindUniqueArgs";
import { CreateAzureConnectionArgs } from "./CreateAzureConnectionArgs";
import { UpdateAzureConnectionArgs } from "./UpdateAzureConnectionArgs";
import { DeleteAzureConnectionArgs } from "./DeleteAzureConnectionArgs";
import { AzureConnectionService } from "../azureConnection.service";
@graphql.Resolver(() => AzureConnection)
export class AzureConnectionResolverBase {
  constructor(protected readonly service: AzureConnectionService) {}

  async _azureConnectionsMeta(
    @graphql.Args() args: AzureConnectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AzureConnection])
  async azureConnections(
    @graphql.Args() args: AzureConnectionFindManyArgs
  ): Promise<AzureConnection[]> {
    return this.service.azureConnections(args);
  }

  @graphql.Query(() => AzureConnection, { nullable: true })
  async azureConnection(
    @graphql.Args() args: AzureConnectionFindUniqueArgs
  ): Promise<AzureConnection | null> {
    const result = await this.service.azureConnection(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AzureConnection)
  async createAzureConnection(
    @graphql.Args() args: CreateAzureConnectionArgs
  ): Promise<AzureConnection> {
    return await this.service.createAzureConnection({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => AzureConnection)
  async updateAzureConnection(
    @graphql.Args() args: UpdateAzureConnectionArgs
  ): Promise<AzureConnection | null> {
    try {
      return await this.service.updateAzureConnection({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AzureConnection)
  async deleteAzureConnection(
    @graphql.Args() args: DeleteAzureConnectionArgs
  ): Promise<AzureConnection | null> {
    try {
      return await this.service.deleteAzureConnection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
