/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LlmIntegrationService } from "../llmIntegration.service";
import { LlmIntegrationCreateInput } from "./LlmIntegrationCreateInput";
import { LlmIntegration } from "./LlmIntegration";
import { LlmIntegrationFindManyArgs } from "./LlmIntegrationFindManyArgs";
import { LlmIntegrationWhereUniqueInput } from "./LlmIntegrationWhereUniqueInput";
import { LlmIntegrationUpdateInput } from "./LlmIntegrationUpdateInput";

export class LlmIntegrationControllerBase {
  constructor(protected readonly service: LlmIntegrationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: LlmIntegration })
  async createLlmIntegration(
    @common.Body() data: LlmIntegrationCreateInput
  ): Promise<LlmIntegration> {
    return await this.service.createLlmIntegration({
      data: {
        ...data,

        promptHandler: data.promptHandler
          ? {
              connect: data.promptHandler,
            }
          : undefined,
      },
      select: {
        apiEndpoint: true,
        apiKeyName: true,
        createdAt: true,
        id: true,
        modelUsed: true,

        promptHandler: {
          select: {
            id: true,
          },
        },

        provider: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [LlmIntegration] })
  @ApiNestedQuery(LlmIntegrationFindManyArgs)
  async llmIntegrations(
    @common.Req() request: Request
  ): Promise<LlmIntegration[]> {
    const args = plainToClass(LlmIntegrationFindManyArgs, request.query);
    return this.service.llmIntegrations({
      ...args,
      select: {
        apiEndpoint: true,
        apiKeyName: true,
        createdAt: true,
        id: true,
        modelUsed: true,

        promptHandler: {
          select: {
            id: true,
          },
        },

        provider: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: LlmIntegration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async llmIntegration(
    @common.Param() params: LlmIntegrationWhereUniqueInput
  ): Promise<LlmIntegration | null> {
    const result = await this.service.llmIntegration({
      where: params,
      select: {
        apiEndpoint: true,
        apiKeyName: true,
        createdAt: true,
        id: true,
        modelUsed: true,

        promptHandler: {
          select: {
            id: true,
          },
        },

        provider: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: LlmIntegration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateLlmIntegration(
    @common.Param() params: LlmIntegrationWhereUniqueInput,
    @common.Body() data: LlmIntegrationUpdateInput
  ): Promise<LlmIntegration | null> {
    try {
      return await this.service.updateLlmIntegration({
        where: params,
        data: {
          ...data,

          promptHandler: data.promptHandler
            ? {
                connect: data.promptHandler,
              }
            : undefined,
        },
        select: {
          apiEndpoint: true,
          apiKeyName: true,
          createdAt: true,
          id: true,
          modelUsed: true,

          promptHandler: {
            select: {
              id: true,
            },
          },

          provider: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: LlmIntegration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteLlmIntegration(
    @common.Param() params: LlmIntegrationWhereUniqueInput
  ): Promise<LlmIntegration | null> {
    try {
      return await this.service.deleteLlmIntegration({
        where: params,
        select: {
          apiEndpoint: true,
          apiKeyName: true,
          createdAt: true,
          id: true,
          modelUsed: true,

          promptHandler: {
            select: {
              id: true,
            },
          },

          provider: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
