/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  LlmIntegration as PrismaLlmIntegration,
  PromptHandler as PrismaPromptHandler,
} from "@prisma/client";

export class LlmIntegrationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.LlmIntegrationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.llmIntegration.count(args);
  }

  async llmIntegrations(
    args: Prisma.LlmIntegrationFindManyArgs
  ): Promise<PrismaLlmIntegration[]> {
    return this.prisma.llmIntegration.findMany(args);
  }
  async llmIntegration(
    args: Prisma.LlmIntegrationFindUniqueArgs
  ): Promise<PrismaLlmIntegration | null> {
    return this.prisma.llmIntegration.findUnique(args);
  }
  async createLlmIntegration(
    args: Prisma.LlmIntegrationCreateArgs
  ): Promise<PrismaLlmIntegration> {
    return this.prisma.llmIntegration.create(args);
  }
  async updateLlmIntegration(
    args: Prisma.LlmIntegrationUpdateArgs
  ): Promise<PrismaLlmIntegration> {
    return this.prisma.llmIntegration.update(args);
  }
  async deleteLlmIntegration(
    args: Prisma.LlmIntegrationDeleteArgs
  ): Promise<PrismaLlmIntegration> {
    return this.prisma.llmIntegration.delete(args);
  }

  async getPromptHandler(
    parentId: string
  ): Promise<PrismaPromptHandler | null> {
    return this.prisma.llmIntegration
      .findUnique({
        where: { id: parentId },
      })
      .promptHandler();
  }
}
