/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { LlmIntegration } from "./LlmIntegration";
import { LlmIntegrationCountArgs } from "./LlmIntegrationCountArgs";
import { LlmIntegrationFindManyArgs } from "./LlmIntegrationFindManyArgs";
import { LlmIntegrationFindUniqueArgs } from "./LlmIntegrationFindUniqueArgs";
import { CreateLlmIntegrationArgs } from "./CreateLlmIntegrationArgs";
import { UpdateLlmIntegrationArgs } from "./UpdateLlmIntegrationArgs";
import { DeleteLlmIntegrationArgs } from "./DeleteLlmIntegrationArgs";
import { PromptHandler } from "../../promptHandler/base/PromptHandler";
import { LlmIntegrationService } from "../llmIntegration.service";
@graphql.Resolver(() => LlmIntegration)
export class LlmIntegrationResolverBase {
  constructor(protected readonly service: LlmIntegrationService) {}

  async _llmIntegrationsMeta(
    @graphql.Args() args: LlmIntegrationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [LlmIntegration])
  async llmIntegrations(
    @graphql.Args() args: LlmIntegrationFindManyArgs
  ): Promise<LlmIntegration[]> {
    return this.service.llmIntegrations(args);
  }

  @graphql.Query(() => LlmIntegration, { nullable: true })
  async llmIntegration(
    @graphql.Args() args: LlmIntegrationFindUniqueArgs
  ): Promise<LlmIntegration | null> {
    const result = await this.service.llmIntegration(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => LlmIntegration)
  async createLlmIntegration(
    @graphql.Args() args: CreateLlmIntegrationArgs
  ): Promise<LlmIntegration> {
    return await this.service.createLlmIntegration({
      ...args,
      data: {
        ...args.data,

        promptHandler: args.data.promptHandler
          ? {
              connect: args.data.promptHandler,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => LlmIntegration)
  async updateLlmIntegration(
    @graphql.Args() args: UpdateLlmIntegrationArgs
  ): Promise<LlmIntegration | null> {
    try {
      return await this.service.updateLlmIntegration({
        ...args,
        data: {
          ...args.data,

          promptHandler: args.data.promptHandler
            ? {
                connect: args.data.promptHandler,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => LlmIntegration)
  async deleteLlmIntegration(
    @graphql.Args() args: DeleteLlmIntegrationArgs
  ): Promise<LlmIntegration | null> {
    try {
      return await this.service.deleteLlmIntegration(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => PromptHandler, {
    nullable: true,
    name: "promptHandler",
  })
  async getPromptHandler(
    @graphql.Parent() parent: LlmIntegration
  ): Promise<PromptHandler | null> {
    const result = await this.service.getPromptHandler(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
