/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CloudConnectionListRelationFilter } from "../../cloudConnection/base/CloudConnectionListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { DeploymentListRelationFilter } from "../../deployment/base/DeploymentListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";

@InputType()
class UserProfileWhereInput {
  @ApiProperty({
    required: false,
    type: () => CloudConnectionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CloudConnectionListRelationFilter)
  @IsOptional()
  @Field(() => CloudConnectionListRelationFilter, {
    nullable: true,
  })
  cloudConnections?: CloudConnectionListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => DeploymentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DeploymentListRelationFilter)
  @IsOptional()
  @Field(() => DeploymentListRelationFilter, {
    nullable: true,
  })
  deployments?: DeploymentListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  role?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  sshKey?: StringNullableFilter;
}

export { UserProfileWhereInput as UserProfileWhereInput };
