/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserProfileService } from "../userProfile.service";
import { UserProfileCreateInput } from "./UserProfileCreateInput";
import { UserProfile } from "./UserProfile";
import { UserProfileFindManyArgs } from "./UserProfileFindManyArgs";
import { UserProfileWhereUniqueInput } from "./UserProfileWhereUniqueInput";
import { UserProfileUpdateInput } from "./UserProfileUpdateInput";
import { CloudConnectionFindManyArgs } from "../../cloudConnection/base/CloudConnectionFindManyArgs";
import { CloudConnection } from "../../cloudConnection/base/CloudConnection";
import { CloudConnectionWhereUniqueInput } from "../../cloudConnection/base/CloudConnectionWhereUniqueInput";
import { DeploymentFindManyArgs } from "../../deployment/base/DeploymentFindManyArgs";
import { Deployment } from "../../deployment/base/Deployment";
import { DeploymentWhereUniqueInput } from "../../deployment/base/DeploymentWhereUniqueInput";

export class UserProfileControllerBase {
  constructor(protected readonly service: UserProfileService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserProfile })
  async createUserProfile(
    @common.Body() data: UserProfileCreateInput
  ): Promise<UserProfile> {
    return await this.service.createUserProfile({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        role: true,
        sshKey: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [UserProfile] })
  @ApiNestedQuery(UserProfileFindManyArgs)
  async userProfiles(@common.Req() request: Request): Promise<UserProfile[]> {
    const args = plainToClass(UserProfileFindManyArgs, request.query);
    return this.service.userProfiles({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        role: true,
        sshKey: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async userProfile(
    @common.Param() params: UserProfileWhereUniqueInput
  ): Promise<UserProfile | null> {
    const result = await this.service.userProfile({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        role: true,
        sshKey: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUserProfile(
    @common.Param() params: UserProfileWhereUniqueInput,
    @common.Body() data: UserProfileUpdateInput
  ): Promise<UserProfile | null> {
    try {
      return await this.service.updateUserProfile({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          name: true,
          role: true,
          sshKey: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUserProfile(
    @common.Param() params: UserProfileWhereUniqueInput
  ): Promise<UserProfile | null> {
    try {
      return await this.service.deleteUserProfile({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          name: true,
          role: true,
          sshKey: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/cloudConnections")
  @ApiNestedQuery(CloudConnectionFindManyArgs)
  async findCloudConnections(
    @common.Req() request: Request,
    @common.Param() params: UserProfileWhereUniqueInput
  ): Promise<CloudConnection[]> {
    const query = plainToClass(CloudConnectionFindManyArgs, request.query);
    const results = await this.service.findCloudConnections(params.id, {
      ...query,
      select: {
        accessKey: true,
        createdAt: true,
        id: true,
        provider: true,
        region: true,
        updatedAt: true,

        userProfile: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/cloudConnections")
  async connectCloudConnections(
    @common.Param() params: UserProfileWhereUniqueInput,
    @common.Body() body: CloudConnectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cloudConnections: {
        connect: body,
      },
    };
    await this.service.updateUserProfile({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/cloudConnections")
  async updateCloudConnections(
    @common.Param() params: UserProfileWhereUniqueInput,
    @common.Body() body: CloudConnectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cloudConnections: {
        set: body,
      },
    };
    await this.service.updateUserProfile({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/cloudConnections")
  async disconnectCloudConnections(
    @common.Param() params: UserProfileWhereUniqueInput,
    @common.Body() body: CloudConnectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cloudConnections: {
        disconnect: body,
      },
    };
    await this.service.updateUserProfile({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/deployments")
  @ApiNestedQuery(DeploymentFindManyArgs)
  async findDeployments(
    @common.Req() request: Request,
    @common.Param() params: UserProfileWhereUniqueInput
  ): Promise<Deployment[]> {
    const query = plainToClass(DeploymentFindManyArgs, request.query);
    const results = await this.service.findDeployments(params.id, {
      ...query,
      select: {
        autoTerminateAt: true,
        createdAt: true,
        environment: true,
        id: true,
        region: true,
        requestPrompt: true,
        resolvedConfig: true,
        status: true,
        updatedAt: true,

        userProfile: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/deployments")
  async connectDeployments(
    @common.Param() params: UserProfileWhereUniqueInput,
    @common.Body() body: DeploymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deployments: {
        connect: body,
      },
    };
    await this.service.updateUserProfile({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/deployments")
  async updateDeployments(
    @common.Param() params: UserProfileWhereUniqueInput,
    @common.Body() body: DeploymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deployments: {
        set: body,
      },
    };
    await this.service.updateUserProfile({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/deployments")
  async disconnectDeployments(
    @common.Param() params: UserProfileWhereUniqueInput,
    @common.Body() body: DeploymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      deployments: {
        disconnect: body,
      },
    };
    await this.service.updateUserProfile({
      where: params,
      data,
      select: { id: true },
    });
  }
}
