/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  PromptHandler as PrismaPromptHandler,
  LlmIntegration as PrismaLlmIntegration,
  Deployment as PrismaDeployment,
} from "@prisma/client";

export class PromptHandlerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PromptHandlerCountArgs, "select">
  ): Promise<number> {
    return this.prisma.promptHandler.count(args);
  }

  async promptHandlers(
    args: Prisma.PromptHandlerFindManyArgs
  ): Promise<PrismaPromptHandler[]> {
    return this.prisma.promptHandler.findMany(args);
  }
  async promptHandler(
    args: Prisma.PromptHandlerFindUniqueArgs
  ): Promise<PrismaPromptHandler | null> {
    return this.prisma.promptHandler.findUnique(args);
  }
  async createPromptHandler(
    args: Prisma.PromptHandlerCreateArgs
  ): Promise<PrismaPromptHandler> {
    return this.prisma.promptHandler.create(args);
  }
  async updatePromptHandler(
    args: Prisma.PromptHandlerUpdateArgs
  ): Promise<PrismaPromptHandler> {
    return this.prisma.promptHandler.update(args);
  }
  async deletePromptHandler(
    args: Prisma.PromptHandlerDeleteArgs
  ): Promise<PrismaPromptHandler> {
    return this.prisma.promptHandler.delete(args);
  }

  async findLlmIntegrations(
    parentId: string,
    args: Prisma.LlmIntegrationFindManyArgs
  ): Promise<PrismaLlmIntegration[]> {
    return this.prisma.promptHandler
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .llmIntegrations(args);
  }

  async getDeployment(parentId: string): Promise<PrismaDeployment | null> {
    return this.prisma.promptHandler
      .findUnique({
        where: { id: parentId },
      })
      .deployment();
  }
}
