/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DeploymentWhereUniqueInput } from "../../deployment/base/DeploymentWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { LlmIntegrationListRelationFilter } from "../../llmIntegration/base/LlmIntegrationListRelationFilter";
import { JsonFilter } from "../../util/JsonFilter";

@InputType()
class PromptHandlerWhereInput {
  @ApiProperty({
    required: false,
    type: () => DeploymentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DeploymentWhereUniqueInput)
  @IsOptional()
  @Field(() => DeploymentWhereUniqueInput, {
    nullable: true,
  })
  deployment?: DeploymentWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  detectedOs?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  inputPrompt?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => LlmIntegrationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => LlmIntegrationListRelationFilter)
  @IsOptional()
  @Field(() => LlmIntegrationListRelationFilter, {
    nullable: true,
  })
  llmIntegrations?: LlmIntegrationListRelationFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  parsedInstructions?: JsonFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  resourcesRequested?: JsonFilter;
}

export { PromptHandlerWhereInput as PromptHandlerWhereInput };
