/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PromptHandler } from "./PromptHandler";
import { PromptHandlerCountArgs } from "./PromptHandlerCountArgs";
import { PromptHandlerFindManyArgs } from "./PromptHandlerFindManyArgs";
import { PromptHandlerFindUniqueArgs } from "./PromptHandlerFindUniqueArgs";
import { CreatePromptHandlerArgs } from "./CreatePromptHandlerArgs";
import { UpdatePromptHandlerArgs } from "./UpdatePromptHandlerArgs";
import { DeletePromptHandlerArgs } from "./DeletePromptHandlerArgs";
import { LlmIntegrationFindManyArgs } from "../../llmIntegration/base/LlmIntegrationFindManyArgs";
import { LlmIntegration } from "../../llmIntegration/base/LlmIntegration";
import { Deployment } from "../../deployment/base/Deployment";
import { PromptHandlerService } from "../promptHandler.service";
@graphql.Resolver(() => PromptHandler)
export class PromptHandlerResolverBase {
  constructor(protected readonly service: PromptHandlerService) {}

  async _promptHandlersMeta(
    @graphql.Args() args: PromptHandlerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PromptHandler])
  async promptHandlers(
    @graphql.Args() args: PromptHandlerFindManyArgs
  ): Promise<PromptHandler[]> {
    return this.service.promptHandlers(args);
  }

  @graphql.Query(() => PromptHandler, { nullable: true })
  async promptHandler(
    @graphql.Args() args: PromptHandlerFindUniqueArgs
  ): Promise<PromptHandler | null> {
    const result = await this.service.promptHandler(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PromptHandler)
  async createPromptHandler(
    @graphql.Args() args: CreatePromptHandlerArgs
  ): Promise<PromptHandler> {
    return await this.service.createPromptHandler({
      ...args,
      data: {
        ...args.data,

        deployment: args.data.deployment
          ? {
              connect: args.data.deployment,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => PromptHandler)
  async updatePromptHandler(
    @graphql.Args() args: UpdatePromptHandlerArgs
  ): Promise<PromptHandler | null> {
    try {
      return await this.service.updatePromptHandler({
        ...args,
        data: {
          ...args.data,

          deployment: args.data.deployment
            ? {
                connect: args.data.deployment,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PromptHandler)
  async deletePromptHandler(
    @graphql.Args() args: DeletePromptHandlerArgs
  ): Promise<PromptHandler | null> {
    try {
      return await this.service.deletePromptHandler(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [LlmIntegration], { name: "llmIntegrations" })
  async findLlmIntegrations(
    @graphql.Parent() parent: PromptHandler,
    @graphql.Args() args: LlmIntegrationFindManyArgs
  ): Promise<LlmIntegration[]> {
    const results = await this.service.findLlmIntegrations(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Deployment, {
    nullable: true,
    name: "deployment",
  })
  async getDeployment(
    @graphql.Parent() parent: PromptHandler
  ): Promise<Deployment | null> {
    const result = await this.service.getDeployment(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
