/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PromptHandlerService } from "../promptHandler.service";
import { PromptHandlerCreateInput } from "./PromptHandlerCreateInput";
import { PromptHandler } from "./PromptHandler";
import { PromptHandlerFindManyArgs } from "./PromptHandlerFindManyArgs";
import { PromptHandlerWhereUniqueInput } from "./PromptHandlerWhereUniqueInput";
import { PromptHandlerUpdateInput } from "./PromptHandlerUpdateInput";
import { LlmIntegrationFindManyArgs } from "../../llmIntegration/base/LlmIntegrationFindManyArgs";
import { LlmIntegration } from "../../llmIntegration/base/LlmIntegration";
import { LlmIntegrationWhereUniqueInput } from "../../llmIntegration/base/LlmIntegrationWhereUniqueInput";

export class PromptHandlerControllerBase {
  constructor(protected readonly service: PromptHandlerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PromptHandler })
  async createPromptHandler(
    @common.Body() data: PromptHandlerCreateInput
  ): Promise<PromptHandler> {
    return await this.service.createPromptHandler({
      data: {
        ...data,

        deployment: data.deployment
          ? {
              connect: data.deployment,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        deployment: {
          select: {
            id: true,
          },
        },

        detectedOs: true,
        id: true,
        inputPrompt: true,
        parsedInstructions: true,
        resourcesRequested: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [PromptHandler] })
  @ApiNestedQuery(PromptHandlerFindManyArgs)
  async promptHandlers(
    @common.Req() request: Request
  ): Promise<PromptHandler[]> {
    const args = plainToClass(PromptHandlerFindManyArgs, request.query);
    return this.service.promptHandlers({
      ...args,
      select: {
        createdAt: true,

        deployment: {
          select: {
            id: true,
          },
        },

        detectedOs: true,
        id: true,
        inputPrompt: true,
        parsedInstructions: true,
        resourcesRequested: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PromptHandler })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async promptHandler(
    @common.Param() params: PromptHandlerWhereUniqueInput
  ): Promise<PromptHandler | null> {
    const result = await this.service.promptHandler({
      where: params,
      select: {
        createdAt: true,

        deployment: {
          select: {
            id: true,
          },
        },

        detectedOs: true,
        id: true,
        inputPrompt: true,
        parsedInstructions: true,
        resourcesRequested: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PromptHandler })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePromptHandler(
    @common.Param() params: PromptHandlerWhereUniqueInput,
    @common.Body() data: PromptHandlerUpdateInput
  ): Promise<PromptHandler | null> {
    try {
      return await this.service.updatePromptHandler({
        where: params,
        data: {
          ...data,

          deployment: data.deployment
            ? {
                connect: data.deployment,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          deployment: {
            select: {
              id: true,
            },
          },

          detectedOs: true,
          id: true,
          inputPrompt: true,
          parsedInstructions: true,
          resourcesRequested: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PromptHandler })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePromptHandler(
    @common.Param() params: PromptHandlerWhereUniqueInput
  ): Promise<PromptHandler | null> {
    try {
      return await this.service.deletePromptHandler({
        where: params,
        select: {
          createdAt: true,

          deployment: {
            select: {
              id: true,
            },
          },

          detectedOs: true,
          id: true,
          inputPrompt: true,
          parsedInstructions: true,
          resourcesRequested: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/llmIntegrations")
  @ApiNestedQuery(LlmIntegrationFindManyArgs)
  async findLlmIntegrations(
    @common.Req() request: Request,
    @common.Param() params: PromptHandlerWhereUniqueInput
  ): Promise<LlmIntegration[]> {
    const query = plainToClass(LlmIntegrationFindManyArgs, request.query);
    const results = await this.service.findLlmIntegrations(params.id, {
      ...query,
      select: {
        apiEndpoint: true,
        apiKeyName: true,
        createdAt: true,
        id: true,
        modelUsed: true,

        promptHandler: {
          select: {
            id: true,
          },
        },

        provider: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/llmIntegrations")
  async connectLlmIntegrations(
    @common.Param() params: PromptHandlerWhereUniqueInput,
    @common.Body() body: LlmIntegrationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      llmIntegrations: {
        connect: body,
      },
    };
    await this.service.updatePromptHandler({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/llmIntegrations")
  async updateLlmIntegrations(
    @common.Param() params: PromptHandlerWhereUniqueInput,
    @common.Body() body: LlmIntegrationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      llmIntegrations: {
        set: body,
      },
    };
    await this.service.updatePromptHandler({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/llmIntegrations")
  async disconnectLlmIntegrations(
    @common.Param() params: PromptHandlerWhereUniqueInput,
    @common.Body() body: LlmIntegrationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      llmIntegrations: {
        disconnect: body,
      },
    };
    await this.service.updatePromptHandler({
      where: params,
      data,
      select: { id: true },
    });
  }
}
