/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, ProviderLog as PrismaProviderLog } from "@prisma/client";

export class ProviderLogServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ProviderLogCountArgs, "select">
  ): Promise<number> {
    return this.prisma.providerLog.count(args);
  }

  async providerLogs(
    args: Prisma.ProviderLogFindManyArgs
  ): Promise<PrismaProviderLog[]> {
    return this.prisma.providerLog.findMany(args);
  }
  async providerLog(
    args: Prisma.ProviderLogFindUniqueArgs
  ): Promise<PrismaProviderLog | null> {
    return this.prisma.providerLog.findUnique(args);
  }
  async createProviderLog(
    args: Prisma.ProviderLogCreateArgs
  ): Promise<PrismaProviderLog> {
    return this.prisma.providerLog.create(args);
  }
  async updateProviderLog(
    args: Prisma.ProviderLogUpdateArgs
  ): Promise<PrismaProviderLog> {
    return this.prisma.providerLog.update(args);
  }
  async deleteProviderLog(
    args: Prisma.ProviderLogDeleteArgs
  ): Promise<PrismaProviderLog> {
    return this.prisma.providerLog.delete(args);
  }
}
