/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProviderLog } from "./ProviderLog";
import { ProviderLogCountArgs } from "./ProviderLogCountArgs";
import { ProviderLogFindManyArgs } from "./ProviderLogFindManyArgs";
import { ProviderLogFindUniqueArgs } from "./ProviderLogFindUniqueArgs";
import { CreateProviderLogArgs } from "./CreateProviderLogArgs";
import { UpdateProviderLogArgs } from "./UpdateProviderLogArgs";
import { DeleteProviderLogArgs } from "./DeleteProviderLogArgs";
import { ProviderLogService } from "../providerLog.service";
@graphql.Resolver(() => ProviderLog)
export class ProviderLogResolverBase {
  constructor(protected readonly service: ProviderLogService) {}

  async _providerLogsMeta(
    @graphql.Args() args: ProviderLogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProviderLog])
  async providerLogs(
    @graphql.Args() args: ProviderLogFindManyArgs
  ): Promise<ProviderLog[]> {
    return this.service.providerLogs(args);
  }

  @graphql.Query(() => ProviderLog, { nullable: true })
  async providerLog(
    @graphql.Args() args: ProviderLogFindUniqueArgs
  ): Promise<ProviderLog | null> {
    const result = await this.service.providerLog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProviderLog)
  async createProviderLog(
    @graphql.Args() args: CreateProviderLogArgs
  ): Promise<ProviderLog> {
    return await this.service.createProviderLog({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => ProviderLog)
  async updateProviderLog(
    @graphql.Args() args: UpdateProviderLogArgs
  ): Promise<ProviderLog | null> {
    try {
      return await this.service.updateProviderLog({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ProviderLog)
  async deleteProviderLog(
    @graphql.Args() args: DeleteProviderLogArgs
  ): Promise<ProviderLog | null> {
    try {
      return await this.service.deleteProviderLog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
