/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProviderLogService } from "../providerLog.service";
import { ProviderLogCreateInput } from "./ProviderLogCreateInput";
import { ProviderLog } from "./ProviderLog";
import { ProviderLogFindManyArgs } from "./ProviderLogFindManyArgs";
import { ProviderLogWhereUniqueInput } from "./ProviderLogWhereUniqueInput";
import { ProviderLogUpdateInput } from "./ProviderLogUpdateInput";

export class ProviderLogControllerBase {
  constructor(protected readonly service: ProviderLogService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProviderLog })
  async createProviderLog(
    @common.Body() data: ProviderLogCreateInput
  ): Promise<ProviderLog> {
    return await this.service.createProviderLog({
      data: data,
      select: {
        action: true,
        createdAt: true,
        id: true,
        provider: true,
        request: true,
        response: true,
        status: true,
        timestamp: true,
        updatedAt: true,
        userProfile: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ProviderLog] })
  @ApiNestedQuery(ProviderLogFindManyArgs)
  async providerLogs(@common.Req() request: Request): Promise<ProviderLog[]> {
    const args = plainToClass(ProviderLogFindManyArgs, request.query);
    return this.service.providerLogs({
      ...args,
      select: {
        action: true,
        createdAt: true,
        id: true,
        provider: true,
        request: true,
        response: true,
        status: true,
        timestamp: true,
        updatedAt: true,
        userProfile: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProviderLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async providerLog(
    @common.Param() params: ProviderLogWhereUniqueInput
  ): Promise<ProviderLog | null> {
    const result = await this.service.providerLog({
      where: params,
      select: {
        action: true,
        createdAt: true,
        id: true,
        provider: true,
        request: true,
        response: true,
        status: true,
        timestamp: true,
        updatedAt: true,
        userProfile: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProviderLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProviderLog(
    @common.Param() params: ProviderLogWhereUniqueInput,
    @common.Body() data: ProviderLogUpdateInput
  ): Promise<ProviderLog | null> {
    try {
      return await this.service.updateProviderLog({
        where: params,
        data: data,
        select: {
          action: true,
          createdAt: true,
          id: true,
          provider: true,
          request: true,
          response: true,
          status: true,
          timestamp: true,
          updatedAt: true,
          userProfile: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProviderLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProviderLog(
    @common.Param() params: ProviderLogWhereUniqueInput
  ): Promise<ProviderLog | null> {
    try {
      return await this.service.deleteProviderLog({
        where: params,
        select: {
          action: true,
          createdAt: true,
          id: true,
          provider: true,
          request: true,
          response: true,
          status: true,
          timestamp: true,
          updatedAt: true,
          userProfile: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
