/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RegionService } from "../region.service";
import { RegionCreateInput } from "./RegionCreateInput";
import { Region } from "./Region";
import { RegionFindManyArgs } from "./RegionFindManyArgs";
import { RegionWhereUniqueInput } from "./RegionWhereUniqueInput";
import { RegionUpdateInput } from "./RegionUpdateInput";
import { InstanceTemplateFindManyArgs } from "../../instanceTemplate/base/InstanceTemplateFindManyArgs";
import { InstanceTemplate } from "../../instanceTemplate/base/InstanceTemplate";
import { InstanceTemplateWhereUniqueInput } from "../../instanceTemplate/base/InstanceTemplateWhereUniqueInput";

export class RegionControllerBase {
  constructor(protected readonly service: RegionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Region })
  async createRegion(@common.Body() data: RegionCreateInput): Promise<Region> {
    return await this.service.createRegion({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        provider: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Region] })
  @ApiNestedQuery(RegionFindManyArgs)
  async regions(@common.Req() request: Request): Promise<Region[]> {
    const args = plainToClass(RegionFindManyArgs, request.query);
    return this.service.regions({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        provider: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Region })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async region(
    @common.Param() params: RegionWhereUniqueInput
  ): Promise<Region | null> {
    const result = await this.service.region({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        provider: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Region })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRegion(
    @common.Param() params: RegionWhereUniqueInput,
    @common.Body() data: RegionUpdateInput
  ): Promise<Region | null> {
    try {
      return await this.service.updateRegion({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          provider: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Region })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRegion(
    @common.Param() params: RegionWhereUniqueInput
  ): Promise<Region | null> {
    try {
      return await this.service.deleteRegion({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          provider: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/instanceTemplates")
  @ApiNestedQuery(InstanceTemplateFindManyArgs)
  async findInstanceTemplates(
    @common.Req() request: Request,
    @common.Param() params: RegionWhereUniqueInput
  ): Promise<InstanceTemplate[]> {
    const query = plainToClass(InstanceTemplateFindManyArgs, request.query);
    const results = await this.service.findInstanceTemplates(params.id, {
      ...query,
      select: {
        cpu: true,
        createdAt: true,
        hasGpu: true,
        id: true,
        memoryGb: true,
        name: true,
        provider: true,

        region: {
          select: {
            id: true,
          },
        },

        storageGb: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/instanceTemplates")
  async connectInstanceTemplates(
    @common.Param() params: RegionWhereUniqueInput,
    @common.Body() body: InstanceTemplateWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      instanceTemplates: {
        connect: body,
      },
    };
    await this.service.updateRegion({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/instanceTemplates")
  async updateInstanceTemplates(
    @common.Param() params: RegionWhereUniqueInput,
    @common.Body() body: InstanceTemplateWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      instanceTemplates: {
        set: body,
      },
    };
    await this.service.updateRegion({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/instanceTemplates")
  async disconnectInstanceTemplates(
    @common.Param() params: RegionWhereUniqueInput,
    @common.Body() body: InstanceTemplateWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      instanceTemplates: {
        disconnect: body,
      },
    };
    await this.service.updateRegion({
      where: params,
      data,
      select: { id: true },
    });
  }
}
