/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, AwsConnection as PrismaAwsConnection } from "@prisma/client";

export class AwsConnectionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AwsConnectionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.awsConnection.count(args);
  }

  async awsConnections(
    args: Prisma.AwsConnectionFindManyArgs
  ): Promise<PrismaAwsConnection[]> {
    return this.prisma.awsConnection.findMany(args);
  }
  async awsConnection(
    args: Prisma.AwsConnectionFindUniqueArgs
  ): Promise<PrismaAwsConnection | null> {
    return this.prisma.awsConnection.findUnique(args);
  }
  async createAwsConnection(
    args: Prisma.AwsConnectionCreateArgs
  ): Promise<PrismaAwsConnection> {
    return this.prisma.awsConnection.create(args);
  }
  async updateAwsConnection(
    args: Prisma.AwsConnectionUpdateArgs
  ): Promise<PrismaAwsConnection> {
    return this.prisma.awsConnection.update(args);
  }
  async deleteAwsConnection(
    args: Prisma.AwsConnectionDeleteArgs
  ): Promise<PrismaAwsConnection> {
    return this.prisma.awsConnection.delete(args);
  }
}
