/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AwsConnectionService } from "../awsConnection.service";
import { AwsConnectionCreateInput } from "./AwsConnectionCreateInput";
import { AwsConnection } from "./AwsConnection";
import { AwsConnectionFindManyArgs } from "./AwsConnectionFindManyArgs";
import { AwsConnectionWhereUniqueInput } from "./AwsConnectionWhereUniqueInput";
import { AwsConnectionUpdateInput } from "./AwsConnectionUpdateInput";

export class AwsConnectionControllerBase {
  constructor(protected readonly service: AwsConnectionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AwsConnection })
  async createAwsConnection(
    @common.Body() data: AwsConnectionCreateInput
  ): Promise<AwsConnection> {
    return await this.service.createAwsConnection({
      data: data,
      select: {
        accessKeyId: true,
        createdAt: true,
        id: true,
        region: true,
        secretAccessKey: true,
        sessionToken: true,
        updatedAt: true,
        userProfile: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AwsConnection] })
  @ApiNestedQuery(AwsConnectionFindManyArgs)
  async awsConnections(
    @common.Req() request: Request
  ): Promise<AwsConnection[]> {
    const args = plainToClass(AwsConnectionFindManyArgs, request.query);
    return this.service.awsConnections({
      ...args,
      select: {
        accessKeyId: true,
        createdAt: true,
        id: true,
        region: true,
        secretAccessKey: true,
        sessionToken: true,
        updatedAt: true,
        userProfile: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AwsConnection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async awsConnection(
    @common.Param() params: AwsConnectionWhereUniqueInput
  ): Promise<AwsConnection | null> {
    const result = await this.service.awsConnection({
      where: params,
      select: {
        accessKeyId: true,
        createdAt: true,
        id: true,
        region: true,
        secretAccessKey: true,
        sessionToken: true,
        updatedAt: true,
        userProfile: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AwsConnection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAwsConnection(
    @common.Param() params: AwsConnectionWhereUniqueInput,
    @common.Body() data: AwsConnectionUpdateInput
  ): Promise<AwsConnection | null> {
    try {
      return await this.service.updateAwsConnection({
        where: params,
        data: data,
        select: {
          accessKeyId: true,
          createdAt: true,
          id: true,
          region: true,
          secretAccessKey: true,
          sessionToken: true,
          updatedAt: true,
          userProfile: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AwsConnection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAwsConnection(
    @common.Param() params: AwsConnectionWhereUniqueInput
  ): Promise<AwsConnection | null> {
    try {
      return await this.service.deleteAwsConnection({
        where: params,
        select: {
          accessKeyId: true,
          createdAt: true,
          id: true,
          region: true,
          secretAccessKey: true,
          sessionToken: true,
          updatedAt: true,
          userProfile: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
