/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AwsConnection } from "./AwsConnection";
import { AwsConnectionCountArgs } from "./AwsConnectionCountArgs";
import { AwsConnectionFindManyArgs } from "./AwsConnectionFindManyArgs";
import { AwsConnectionFindUniqueArgs } from "./AwsConnectionFindUniqueArgs";
import { CreateAwsConnectionArgs } from "./CreateAwsConnectionArgs";
import { UpdateAwsConnectionArgs } from "./UpdateAwsConnectionArgs";
import { DeleteAwsConnectionArgs } from "./DeleteAwsConnectionArgs";
import { AwsConnectionService } from "../awsConnection.service";
@graphql.Resolver(() => AwsConnection)
export class AwsConnectionResolverBase {
  constructor(protected readonly service: AwsConnectionService) {}

  async _awsConnectionsMeta(
    @graphql.Args() args: AwsConnectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AwsConnection])
  async awsConnections(
    @graphql.Args() args: AwsConnectionFindManyArgs
  ): Promise<AwsConnection[]> {
    return this.service.awsConnections(args);
  }

  @graphql.Query(() => AwsConnection, { nullable: true })
  async awsConnection(
    @graphql.Args() args: AwsConnectionFindUniqueArgs
  ): Promise<AwsConnection | null> {
    const result = await this.service.awsConnection(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AwsConnection)
  async createAwsConnection(
    @graphql.Args() args: CreateAwsConnectionArgs
  ): Promise<AwsConnection> {
    return await this.service.createAwsConnection({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => AwsConnection)
  async updateAwsConnection(
    @graphql.Args() args: UpdateAwsConnectionArgs
  ): Promise<AwsConnection | null> {
    try {
      return await this.service.updateAwsConnection({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AwsConnection)
  async deleteAwsConnection(
    @graphql.Args() args: DeleteAwsConnectionArgs
  ): Promise<AwsConnection | null> {
    try {
      return await this.service.deleteAwsConnection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
