/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CloudConnectionService } from "../cloudConnection.service";
import { CloudConnectionCreateInput } from "./CloudConnectionCreateInput";
import { CloudConnection } from "./CloudConnection";
import { CloudConnectionFindManyArgs } from "./CloudConnectionFindManyArgs";
import { CloudConnectionWhereUniqueInput } from "./CloudConnectionWhereUniqueInput";
import { CloudConnectionUpdateInput } from "./CloudConnectionUpdateInput";

export class CloudConnectionControllerBase {
  constructor(protected readonly service: CloudConnectionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CloudConnection })
  async createCloudConnection(
    @common.Body() data: CloudConnectionCreateInput
  ): Promise<CloudConnection> {
    return await this.service.createCloudConnection({
      data: {
        ...data,

        userProfile: data.userProfile
          ? {
              connect: data.userProfile,
            }
          : undefined,
      },
      select: {
        accessKey: true,
        createdAt: true,
        id: true,
        provider: true,
        region: true,
        updatedAt: true,

        userProfile: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CloudConnection] })
  @ApiNestedQuery(CloudConnectionFindManyArgs)
  async cloudConnections(
    @common.Req() request: Request
  ): Promise<CloudConnection[]> {
    const args = plainToClass(CloudConnectionFindManyArgs, request.query);
    return this.service.cloudConnections({
      ...args,
      select: {
        accessKey: true,
        createdAt: true,
        id: true,
        provider: true,
        region: true,
        updatedAt: true,

        userProfile: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CloudConnection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async cloudConnection(
    @common.Param() params: CloudConnectionWhereUniqueInput
  ): Promise<CloudConnection | null> {
    const result = await this.service.cloudConnection({
      where: params,
      select: {
        accessKey: true,
        createdAt: true,
        id: true,
        provider: true,
        region: true,
        updatedAt: true,

        userProfile: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CloudConnection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCloudConnection(
    @common.Param() params: CloudConnectionWhereUniqueInput,
    @common.Body() data: CloudConnectionUpdateInput
  ): Promise<CloudConnection | null> {
    try {
      return await this.service.updateCloudConnection({
        where: params,
        data: {
          ...data,

          userProfile: data.userProfile
            ? {
                connect: data.userProfile,
              }
            : undefined,
        },
        select: {
          accessKey: true,
          createdAt: true,
          id: true,
          provider: true,
          region: true,
          updatedAt: true,

          userProfile: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CloudConnection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCloudConnection(
    @common.Param() params: CloudConnectionWhereUniqueInput
  ): Promise<CloudConnection | null> {
    try {
      return await this.service.deleteCloudConnection({
        where: params,
        select: {
          accessKey: true,
          createdAt: true,
          id: true,
          provider: true,
          region: true,
          updatedAt: true,

          userProfile: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
