/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  CloudConnection as PrismaCloudConnection,
  UserProfile as PrismaUserProfile,
} from "@prisma/client";

import { CloudCredentialsInput } from "../CloudCredentialsInput";
import { CloudCredentialsValidation } from "../CloudCredentialsValidation";

export class CloudConnectionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CloudConnectionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.cloudConnection.count(args);
  }

  async cloudConnections(
    args: Prisma.CloudConnectionFindManyArgs
  ): Promise<PrismaCloudConnection[]> {
    return this.prisma.cloudConnection.findMany(args);
  }
  async cloudConnection(
    args: Prisma.CloudConnectionFindUniqueArgs
  ): Promise<PrismaCloudConnection | null> {
    return this.prisma.cloudConnection.findUnique(args);
  }
  async createCloudConnection(
    args: Prisma.CloudConnectionCreateArgs
  ): Promise<PrismaCloudConnection> {
    return this.prisma.cloudConnection.create(args);
  }
  async updateCloudConnection(
    args: Prisma.CloudConnectionUpdateArgs
  ): Promise<PrismaCloudConnection> {
    return this.prisma.cloudConnection.update(args);
  }
  async deleteCloudConnection(
    args: Prisma.CloudConnectionDeleteArgs
  ): Promise<PrismaCloudConnection> {
    return this.prisma.cloudConnection.delete(args);
  }

  async getUserProfile(parentId: string): Promise<PrismaUserProfile | null> {
    return this.prisma.cloudConnection
      .findUnique({
        where: { id: parentId },
      })
      .userProfile();
  }
  async ValidateCloudCredentials(
    args: CloudCredentialsInput
  ): Promise<CloudCredentialsValidation> {
    throw new Error("Not implemented");
  }
}
