/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CloudConnection } from "./CloudConnection";
import { CloudConnectionCountArgs } from "./CloudConnectionCountArgs";
import { CloudConnectionFindManyArgs } from "./CloudConnectionFindManyArgs";
import { CloudConnectionFindUniqueArgs } from "./CloudConnectionFindUniqueArgs";
import { CreateCloudConnectionArgs } from "./CreateCloudConnectionArgs";
import { UpdateCloudConnectionArgs } from "./UpdateCloudConnectionArgs";
import { DeleteCloudConnectionArgs } from "./DeleteCloudConnectionArgs";
import { UserProfile } from "../../userProfile/base/UserProfile";
import { CloudCredentialsInput } from "../CloudCredentialsInput";
import { CloudCredentialsValidation } from "../CloudCredentialsValidation";
import { CloudConnectionService } from "../cloudConnection.service";
@graphql.Resolver(() => CloudConnection)
export class CloudConnectionResolverBase {
  constructor(protected readonly service: CloudConnectionService) {}

  async _cloudConnectionsMeta(
    @graphql.Args() args: CloudConnectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CloudConnection])
  async cloudConnections(
    @graphql.Args() args: CloudConnectionFindManyArgs
  ): Promise<CloudConnection[]> {
    return this.service.cloudConnections(args);
  }

  @graphql.Query(() => CloudConnection, { nullable: true })
  async cloudConnection(
    @graphql.Args() args: CloudConnectionFindUniqueArgs
  ): Promise<CloudConnection | null> {
    const result = await this.service.cloudConnection(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CloudConnection)
  async createCloudConnection(
    @graphql.Args() args: CreateCloudConnectionArgs
  ): Promise<CloudConnection> {
    return await this.service.createCloudConnection({
      ...args,
      data: {
        ...args.data,

        userProfile: args.data.userProfile
          ? {
              connect: args.data.userProfile,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => CloudConnection)
  async updateCloudConnection(
    @graphql.Args() args: UpdateCloudConnectionArgs
  ): Promise<CloudConnection | null> {
    try {
      return await this.service.updateCloudConnection({
        ...args,
        data: {
          ...args.data,

          userProfile: args.data.userProfile
            ? {
                connect: args.data.userProfile,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CloudConnection)
  async deleteCloudConnection(
    @graphql.Args() args: DeleteCloudConnectionArgs
  ): Promise<CloudConnection | null> {
    try {
      return await this.service.deleteCloudConnection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => UserProfile, {
    nullable: true,
    name: "userProfile",
  })
  async getUserProfile(
    @graphql.Parent() parent: CloudConnection
  ): Promise<UserProfile | null> {
    const result = await this.service.getUserProfile(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CloudCredentialsValidation)
  async ValidateCloudCredentials(
    @graphql.Args()
    args: CloudCredentialsInput
  ): Promise<CloudCredentialsValidation> {
    return this.service.ValidateCloudCredentials(args);
  }
}
